# These are supported funding model platforms

github: [Yyg-Masamba] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
other: ['https://telegra.ph/file/2dd694fa7318e79df3423.jpg', 'https://t.me/CollectionMovie_Subtitles'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
